version: '3'
services:
  app:
    user: root
    build: .
    environment:
        BOT_TOKEN: weee # Put bot token here
        # LOG_LEVEL is used to determine how logs should be handled.
        # Values are:
        #   0 - stderr only
        #   1 - logs/<month>-<day>-<year>.log only
        #   anything else: Both 0 and 1.  
        LOG_LEVEL: 2
    volumes:
      - .:/opt/app
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis
  postgres:
    build:
      context: .
      dockerfile: Dockerfile-PG
    environment:
      - POSTGRES_USER=allawesome497
      - POSTGRES_DB=allseeingbot
      - POSTGRES_HOST_AUTH_METHOD=trust
  redis:
    image: redis:6.0.9-alpine
